$(function(){$(window).one("scroll",function(){if(-1===window.location.href.indexOf("updated-min")){var e=$(".post-outer").length,n=0<$(".index-author").length?!0:!1,p=$(".post-outer .ReadMore:first").text(),f,l=-1!==window.location.href.indexOf("/search/label/")?"/feeds/posts/summary/-/"+window.location.href.match(/\/label\/.+\?/)[0].replace(/\/label\//,"").replace("?",""):"/feeds/posts/summary";$.get(l+"?alt=json-in-script&max-results=0",function(m){function b(){Math.ceil(f/e)>$(".nums").width()/
40?0==$("#Pagination .pg-prev").length&&("rtl"===b_dir?$("#Pagination").prepend('<a class="pg-prev">&#xf101;</a>').append('<a class="pg-next">&#xf100;</a>'):$("#Pagination").prepend('<a class="pg-prev">&#xf100;</a>').append('<a class="pg-next">&#xf101;</a>')):$("#Pagination .pg-prev, #Pagination .pg-next").remove()}f=m.feed.openSearch$totalResults.$t;$("#Pagination .nums").prepend('<span class="curr">1</span>');for(i=2;i<=Math.ceil(f/e);i++)$("#Pagination .nums").append("<span>"+i+"</span>");b();
$(window).resize(b);$("body").on("click",".pg-next",function(){$('.nums span:not(".hid-num"):first').text()!=Math.ceil(f/e)-Math.floor($(".nums").width()/40)+1&&$('.nums span:not(".hid-num"):first').addClass("hid-num")});$("body").on("click",".pg-prev",function(){$(".nums span.hid-num:last").removeAttr("class")})},"jsonp");$("body").on("click","#Pagination span:not(.curr)",function(){$(".curr").removeClass("curr");$(this).addClass("curr");$(".post-outer").addClass("opac");var f=$(this).text()*e-e+
1;$.get(l+"?alt=json-in-script&max-results="+e+"&start-index="+f,function(b){$(".post-outer").remove();var a="",c,g;for(c=0;c<b.feed.entry.length;c+=1){for(g=0;g<b.feed.entry[c].link.length;g+=1){var h=b.feed.entry[c].link[g];if("alternate"==h.rel){var d=h.href;d=httpsEnabled?d.replace("http://","https://"):d;break}}g=b.feed.entry[c].summary.$t.replace(/<\S[^>]*>/g,"");g=g.substr(0,100)+" ...";h=b.feed.entry[c].title.$t;var e=b.feed.entry[c].author[0].name.$t,f=void 0!==b.feed.entry[c].author[0].uri?
b.feed.entry[c].author[0].uri.$t:"",l=b.feed.entry[c].published.$t,k=void 0!==b.feed.entry[c].media$thumbnail?b.feed.entry[c].media$thumbnail.url:alt_Img,m=ResizeImg(k,1600);k=-1!==k.indexOf("youtube.com/vi/")?k.replace("/default.","/hqdefault."):rct_cards?ResizeImg(k,t_index_cards[0],t_index_cards[1]):ResizeImg(k,t_index[0],t_index[1]);a=rct_cards?a+"<div class='post-outer notr'><div class='rct-cards'>":a+"<div class='post-outer notr'><div class='index-body'>";a+='<a class="RecentThumb" href="'+
d+'" title="'+h+'">';a+='<span style="background-image:url('+k+');"></span>';a+='<div class="boxs"></div></a>';a+='<h2 class="post-title entry-title" itemprop="name headline"><a href="'+d+'" title="'+h+'">'+h+"</a></h2>";a+='<div class="boxs"></div></a>';a+='<div class="details">';n&&(a+='<span class="index-author" itemprop="author" itemscope="itemscope" itemtype="https://schema.org/Person"><a class="fn g-profile" href="'+f+'" rel="author" title="author profile" data-gapiscan="true" data-onload="true" data-gapiattached="true"><span itemprop="name">'+
e+'</span></a><a class="url" href="" itemprop="url"></a></span>');a+='<span class="index-time"><abbr class="timeago published updated" itemprop="datePublished dateModified" title="'+l+'">'+l+"</abbr></span></div>";a+='<p class="RecentSnippet">'+g+"</p>";a+='<a class="ReadMore" href="'+d+'" title="'+h+'">'+p+"</a>";a+='<a class="ShareIndex fa fa-heart-o" title="Share Post"></a><div class="ShareIndexBut notr">';a+='<a class="fb" href="https://www.facebook.com/sharer/sharer.php?u='+d+'" rel="noopener" target="_blank" title="Share">\uf09a</a>';
a+='<a class="go" href="https://plus.google.com/share?url='+d+'" rel="noopener" target="_blank" title="+1">\uf1a0</a>';a+='<a class="tw" href="https://twitter.com/home?status='+d+'" rel="noopener" target="_blank" title="Tweet">\uf099</a>';a+='<a class="pin" href="https://pinterest.com/pin/create/button/?url'+d+"&amp;media="+m+"&amp;description="+h+'" rel="noopener" target="_blank" title="Pin It">\uf0d2</a>';a+="</div></div></div>"}$(".blog-posts").html(a+'<i class="clear"/>');rct_cards&&(b=Math.round($(".blog-posts").outerWidth()/
240),cards_width(b,20*b-20));$("html,body").stop().animate({scrollTop:$("#Blog1").offset().top});jQuery("abbr.timeago").timeago()},"jsonp")})}else $("#Pagination").remove()})});
